[build]
  command = "npm install && npm run build"
  functions = "functions/"
  publish = "output/"

[template.environment]
  DEFAULT_URL = "URL of the site to be tested"
  MONGODB_CONN_STR = "MongoDB connection string (e.g. mongodb://<username:password>@host:port)"
  MONGODB_DATABASE = "MongoDB database name"
  WPT_API_KEY = "WebPageTest API key"

[[redirects]]
  from = "/api/pingback/:profile"
  to = "/.netlify/functions/pingback?profile=:profile&id=:id&key=:key"
  query = {id = ":id", key = ":key"}
  status = 200

[[redirects]]
  from = "/api/results/:profile"
  to = "/.netlify/functions/results?profile=:profile&from=:from&to=:to"
  query = {from = ":from", to = ":to"}
  status = 200

[[redirects]]
  from = "/api/test/:profile"
  to = "/.netlify/functions/test?profile=:profile"
  status = 200