default:
  name: "BBC One"
  parameters:
    connectivity: "Cable"
    location: "London_EC2"
    runs: 5
    url: "https://www.bbc.co.uk/bbcone"
  budgets:
    -
      metric: "TTFB"
      max: 1000
      alerts:
        - slackAlert